services:
  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    environment:
      - CUSTOM_USER=your_username
      - PASSWORD=your_passwd
      - TITLE=your_title
      - DOCKER_MODS=linuxserver/mods:universal-internationalization
      - LC_ALL=zh_CN.UTF-8
    volumes:
      - ./config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 127.0.0.1:3000:3000
    devices: 
      - "/dev/snd:/dev/snd"
      - "/dev/dri:/dev/dri"
    shm_size: "1gb"
    restart: unless-stopped
