services:
  palworld:
    image: thijsvanloef/palworld-server-docker:latest
    restart: unless-stopped
    container_name: palworld-server
    ports:
      - 8211:8211/udp
      - 27015:27015/udp
    environment:
      - PUID=1000
      - PGID=1000
      - PORT=8211
      - PLAYERS=6
      - SERVER_PASSWORD="your_password"
      - MULTITHREADING=true
      - RCON_ENABLED=true
      - RCON_PORT=25575
      - TZ=Asia/Shanghai
      - ADMIN_PASSWORD="admin_password"
      - COMMUNITY=true  
      - SERVER_NAME="your_palword_name"
    volumes:
      - ./palworld:/palworld/