version: '3'

services:
  looking-glass:
    image: wikihostinc/looking-glass-server
    container_name: looking-glass
    restart: always
    environment:
      - LISTEN_IP=127.0.0.1
      - HTTP_PORT=8081
    network_mode: host